// Result of running refactor asyncAwaitToFnTryPromise at position 4:28
import * as T from "effect/Effect"

export const refactorMe = refactorMe("refactorMe")(function*(arg: string) {
    return yield* T.tryPromise({ try: () => Promise.resolve(arg), catch: error => ({ _tag: "Error1" as const, error }) })
})
